Update python lint and format job actions

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -49,21 +49,20 @@ jobs:
         run: poetry install --with dev --no-interaction --no-root
 
       # Run linting, formatting, etc.
-      # if: success() || failure() is used to ensure all steps run, even if one fails
-      - name: Lint with Ruff
-        run: poetry run ruff check src/ tests/
+      # if success() || failure() is used to ensure all steps run, even if one fails
 
       - name: Format with Black
-        uses: cytopia/docker-black@0.11
-        if: success() || failure()
+        uses: psf/black@stable
         with:
-          path: .
+          options: --check --verbose --diff --color --target-version py311
 
       - name: Format with isort
-        uses: isort/isort-action@v1.1.0
         if: success() || failure()
-        with:
-          configuration: "--check-only --diff --profile black"
+        run: poetry run isort --check-only --diff --profile black
+
+      - name: Lint with Ruff
+        if: success() || failure()
+        run: poetry run ruff check src/ tests/
 
   pytest:
     runs-on: ubuntu-latest
@@ -72,6 +71,7 @@ jobs:
       - uses: GitHubSecurityLab/actions-permissions/monitor@v1
         with:
           config: ${{ vars.PERMISSIONS_CONFIG }}
+
       # Get repo, python, and poetry
       - name: Checkout Repository
         uses: actions/checkout@v4
